/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.config;

import __main__.MainFrame;

/**
 *
 * @author Oussama
 */
public class CONFIG_UI0004_CONFIG_PROJECT_MASTER_DATA_JPANEL extends javax.swing.JPanel {

    /**
     * Creates new form CONFIG_UI0004_CONFIG_PROJECT
     */
    public CONFIG_UI0004_CONFIG_PROJECT_MASTER_DATA_JPANEL() {
        initComponents();
    }

    public CONFIG_UI0004_CONFIG_PROJECT_MASTER_DATA_JPANEL(MainFrame aThis) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        main_tab = new javax.swing.JTabbedPane();
        company_pane = new javax.swing.JPanel();
        company_fields = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        companyPane_field_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        companyPane_field_country = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        companyPane_field_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        companyPane_field_description = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        companyPane_field_address1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        companyPane_field_address2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        companyPane_field_city = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        companyPane_field_website = new javax.swing.JTextField();
        companyPane_field_zip = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        actions_pane = new javax.swing.JPanel();
        companyPane_btn_delete = new javax.swing.JButton();
        companyPane_btn_duplicate = new javax.swing.JButton();
        companyPane_btn_save = new javax.swing.JButton();
        companyPane_msg = new javax.swing.JTextField();
        company_table = new javax.swing.JScrollPane();
        company_jtable = new javax.swing.JTable();
        project_pane = new javax.swing.JPanel();
        family_fields1 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        projectPane_field_id = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        projectPane_field_id2 = new javax.swing.JTextField();
        project_table = new javax.swing.JScrollPane();
        project_jtable = new javax.swing.JTable();
        actions_pane_7 = new javax.swing.JPanel();
        projectPane_msg = new javax.swing.JTextField();
        projectPane_delete = new javax.swing.JButton();
        projectPane_duplicate = new javax.swing.JButton();
        projectPane_save = new javax.swing.JButton();
        family_pane = new javax.swing.JPanel();
        family_fields = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        famillePane_field_id = new javax.swing.JTextField();
        famillePane_field_project = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        famillePane_field_scan_mode = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        famillePane_field_family = new javax.swing.JTextField();
        actions_pane_2 = new javax.swing.JPanel();
        famillePane_msg = new javax.swing.JTextField();
        famillePane_delete = new javax.swing.JButton();
        famillePane_duplicate = new javax.swing.JButton();
        famillePane_save = new javax.swing.JButton();
        famille_table = new javax.swing.JScrollPane();
        famille_jtable = new javax.swing.JTable();
        segment_pane = new javax.swing.JPanel();
        segment_fields = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        segmentPane_field_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        segmentPane_field_segment = new javax.swing.JTextField();
        segmentPane_field_project = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        actions_pane_3 = new javax.swing.JPanel();
        segmentPane_msg = new javax.swing.JTextField();
        segmentPane_delete = new javax.swing.JButton();
        segmentPane_duplicate = new javax.swing.JButton();
        segmentPane_save = new javax.swing.JButton();
        segment_table = new javax.swing.JScrollPane();
        segment_jtable = new javax.swing.JTable();
        workplace_pane = new javax.swing.JPanel();
        workplace_fields = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        workplacePane_field_id = new javax.swing.JTextField();
        workplacePane_field_project = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        workplacePane_field_workplace = new javax.swing.JTextField();
        workplacePane_field_segment = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        actions_pane_4 = new javax.swing.JPanel();
        workplacePane_msg = new javax.swing.JTextField();
        workplacePane_delete = new javax.swing.JButton();
        workplacePane_duplicate = new javax.swing.JButton();
        workplacePane_save = new javax.swing.JButton();
        workplace_table = new javax.swing.JScrollPane();
        workplace_jtable = new javax.swing.JTable();
        magasin_pane = new javax.swing.JPanel();
        magasin_fields = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        magasinPane_field_id = new javax.swing.JTextField();
        magasinPane_field_projet = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        magasinPane_field_magasin = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        magasinPane_field_WhType = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        magasinPane_field_desc = new javax.swing.JTextArea();
        actions_pane_5 = new javax.swing.JPanel();
        magasinPane_msg = new javax.swing.JTextField();
        magasinPane_delete = new javax.swing.JButton();
        magasinPane_duplicate = new javax.swing.JButton();
        magasinPane_save = new javax.swing.JButton();
        magasin_table = new javax.swing.JScrollPane();
        magasin_jtable = new javax.swing.JTable();
        transporter_pane = new javax.swing.JPanel();
        project_fields1 = new javax.swing.JPanel();
        transporterPane_label_id = new javax.swing.JLabel();
        transporterPane_field_id = new javax.swing.JTextField();
        actions_pane_6 = new javax.swing.JPanel();
        transporterPane_field_msg = new javax.swing.JTextField();
        transporterPane_delete = new javax.swing.JButton();
        transporterPane_duplicate = new javax.swing.JButton();
        transporterPane_save = new javax.swing.JButton();
        transporter_table = new javax.swing.JScrollPane();
        transporter_jtable = new javax.swing.JTable();
        segmentPane_msg1 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(36, 65, 86));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pramétrage de base");

        jLabel2.setText("ID");

        companyPane_field_id.setEditable(false);
        companyPane_field_id.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel3.setText("Country");

        companyPane_field_country.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel4.setText("Nom");

        companyPane_field_name.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel5.setText("Description");

        companyPane_field_description.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel6.setText("Adresse 1");

        companyPane_field_address1.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel7.setText("Adresse 2");

        companyPane_field_address2.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel8.setText("Ville");

        companyPane_field_city.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel24.setText("Website");

        companyPane_field_website.setPreferredSize(new java.awt.Dimension(20, 24));

        companyPane_field_zip.setPreferredSize(new java.awt.Dimension(20, 24));

        jLabel25.setText("Zip code");

        javax.swing.GroupLayout company_fieldsLayout = new javax.swing.GroupLayout(company_fields);
        company_fields.setLayout(company_fieldsLayout);
        company_fieldsLayout.setHorizontalGroup(
            company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(company_fieldsLayout.createSequentialGroup()
                .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(company_fieldsLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(companyPane_field_address1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(companyPane_field_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(company_fieldsLayout.createSequentialGroup()
                        .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(company_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(companyPane_field_city, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(company_fieldsLayout.createSequentialGroup()
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(companyPane_field_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(companyPane_field_website, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, company_fieldsLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(companyPane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(companyPane_field_country, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, company_fieldsLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(companyPane_field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(companyPane_field_description, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        company_fieldsLayout.setVerticalGroup(
            company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(company_fieldsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyPane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(companyPane_field_country, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyPane_field_name, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyPane_field_description, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyPane_field_address1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companyPane_field_address2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(company_fieldsLayout.createSequentialGroup()
                        .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyPane_field_website, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))
                    .addGroup(company_fieldsLayout.createSequentialGroup()
                        .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyPane_field_city, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(company_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(companyPane_field_zip, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        companyPane_btn_delete.setText("Supprimer");

        companyPane_btn_duplicate.setText("Dupliquer");

        companyPane_btn_save.setText("Enregistrer");

        companyPane_msg.setEditable(false);
        companyPane_msg.setBackground(new java.awt.Color(255, 255, 255));
        companyPane_msg.setForeground(new java.awt.Color(0, 0, 0));
        companyPane_msg.setCaretColor(new java.awt.Color(255, 0, 0));

        company_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        company_jtable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        company_table.setViewportView(company_jtable);

        javax.swing.GroupLayout actions_paneLayout = new javax.swing.GroupLayout(actions_pane);
        actions_pane.setLayout(actions_paneLayout);
        actions_paneLayout.setHorizontalGroup(
            actions_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(companyPane_btn_save)
                .addGap(18, 18, 18)
                .addComponent(companyPane_btn_duplicate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(companyPane_btn_delete)
                .addGap(32, 32, 32)
                .addComponent(companyPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(company_table, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        actions_paneLayout.setVerticalGroup(
            actions_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actions_paneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(actions_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(companyPane_btn_save)
                    .addComponent(companyPane_btn_duplicate)
                    .addComponent(companyPane_btn_delete)
                    .addComponent(companyPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(company_table, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout company_paneLayout = new javax.swing.GroupLayout(company_pane);
        company_pane.setLayout(company_paneLayout);
        company_paneLayout.setHorizontalGroup(
            company_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, company_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(company_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(company_fields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actions_pane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        company_paneLayout.setVerticalGroup(
            company_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(company_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(company_fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actions_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );

        main_tab.addTab("Société", company_pane);

        jLabel27.setText("ID");

        projectPane_field_id.setEditable(false);

        jLabel28.setText("Abréviation");

        javax.swing.GroupLayout family_fields1Layout = new javax.swing.GroupLayout(family_fields1);
        family_fields1.setLayout(family_fields1Layout);
        family_fields1Layout.setHorizontalGroup(
            family_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(family_fields1Layout.createSequentialGroup()
                .addGroup(family_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(family_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectPane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectPane_field_id2, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        family_fields1Layout.setVerticalGroup(
            family_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, family_fields1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(family_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectPane_field_id, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(family_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projectPane_field_id2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );

        project_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        project_table.setViewportView(project_jtable);

        projectPane_msg.setEditable(false);
        projectPane_msg.setBackground(new java.awt.Color(255, 255, 255));
        projectPane_msg.setForeground(new java.awt.Color(0, 0, 0));

        projectPane_delete.setText("Supprimer");

        projectPane_duplicate.setText("Dupliquer");

        projectPane_save.setText("Enregistrer");

        javax.swing.GroupLayout actions_pane_7Layout = new javax.swing.GroupLayout(actions_pane_7);
        actions_pane_7.setLayout(actions_pane_7Layout);
        actions_pane_7Layout.setHorizontalGroup(
            actions_pane_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_pane_7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectPane_save)
                .addGap(18, 18, 18)
                .addComponent(projectPane_duplicate)
                .addGap(89, 89, 89)
                .addComponent(projectPane_delete)
                .addGap(18, 18, 18)
                .addComponent(projectPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        actions_pane_7Layout.setVerticalGroup(
            actions_pane_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actions_pane_7Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(actions_pane_7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectPane_save)
                    .addComponent(projectPane_duplicate)
                    .addComponent(projectPane_delete)
                    .addComponent(projectPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout project_paneLayout = new javax.swing.GroupLayout(project_pane);
        project_pane.setLayout(project_paneLayout);
        project_paneLayout.setHorizontalGroup(
            project_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(project_table, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(actions_pane_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(project_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(family_fields1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        project_paneLayout.setVerticalGroup(
            project_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(project_paneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(family_fields1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(actions_pane_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(project_table, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main_tab.addTab("Projets", project_pane);

        jLabel9.setText("ID");

        famillePane_field_id.setEditable(false);

        jLabel10.setText("Projet");

        famillePane_field_scan_mode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3" }));
        famillePane_field_scan_mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                famillePane_field_scan_modeActionPerformed(evt);
            }
        });

        jLabel11.setText("Mode de scanne");

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel26.setText("Famille");

        javax.swing.GroupLayout family_fieldsLayout = new javax.swing.GroupLayout(family_fields);
        family_fields.setLayout(family_fieldsLayout);
        family_fieldsLayout.setHorizontalGroup(
            family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(family_fieldsLayout.createSequentialGroup()
                .addGroup(family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(famillePane_field_project, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(famillePane_field_id)
                    .addComponent(famillePane_field_family, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(family_fieldsLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(famillePane_field_scan_mode, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        family_fieldsLayout.setVerticalGroup(
            family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, family_fieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(famillePane_field_id)
                    .addComponent(famillePane_field_scan_mode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(family_fieldsLayout.createSequentialGroup()
                        .addGroup(family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(famillePane_field_project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(family_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(famillePane_field_family, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        famillePane_msg.setEditable(false);
        famillePane_msg.setBackground(new java.awt.Color(255, 255, 255));
        famillePane_msg.setForeground(new java.awt.Color(0, 0, 0));

        famillePane_delete.setText("Supprimer");

        famillePane_duplicate.setText("Dupliquer");

        famillePane_save.setText("Enregistrer");

        javax.swing.GroupLayout actions_pane_2Layout = new javax.swing.GroupLayout(actions_pane_2);
        actions_pane_2.setLayout(actions_pane_2Layout);
        actions_pane_2Layout.setHorizontalGroup(
            actions_pane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_pane_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(famillePane_save)
                .addGap(18, 18, 18)
                .addComponent(famillePane_duplicate)
                .addGap(76, 76, 76)
                .addComponent(famillePane_delete)
                .addGap(18, 18, 18)
                .addComponent(famillePane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        actions_pane_2Layout.setVerticalGroup(
            actions_pane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actions_pane_2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(actions_pane_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(famillePane_save)
                    .addComponent(famillePane_duplicate)
                    .addComponent(famillePane_delete)
                    .addComponent(famillePane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        famille_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        famille_table.setViewportView(famille_jtable);

        javax.swing.GroupLayout family_paneLayout = new javax.swing.GroupLayout(family_pane);
        family_pane.setLayout(family_paneLayout);
        family_paneLayout.setHorizontalGroup(
            family_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, family_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(family_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(famille_table)
                    .addComponent(family_fields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actions_pane_2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        family_paneLayout.setVerticalGroup(
            family_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(family_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(family_fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(actions_pane_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(famille_table, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_tab.addTab("Famille", family_pane);

        jLabel12.setText("ID");

        segmentPane_field_id.setEditable(false);

        jLabel14.setText("Ségment");

        jLabel13.setText("Projet");

        javax.swing.GroupLayout segment_fieldsLayout = new javax.swing.GroupLayout(segment_fields);
        segment_fields.setLayout(segment_fieldsLayout);
        segment_fieldsLayout.setHorizontalGroup(
            segment_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segment_fieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(segment_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(segment_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(segmentPane_field_id, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(segmentPane_field_segment)
                    .addComponent(segmentPane_field_project, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        segment_fieldsLayout.setVerticalGroup(
            segment_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segment_fieldsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(segment_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segmentPane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(segment_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(segmentPane_field_segment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(segment_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(segmentPane_field_project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        segmentPane_msg.setEditable(false);
        segmentPane_msg.setBackground(new java.awt.Color(255, 255, 255));
        segmentPane_msg.setForeground(new java.awt.Color(0, 0, 0));

        segmentPane_delete.setText("Supprimer");

        segmentPane_duplicate.setText("Dupliquer");

        segmentPane_save.setText("Enregistrer");

        javax.swing.GroupLayout actions_pane_3Layout = new javax.swing.GroupLayout(actions_pane_3);
        actions_pane_3.setLayout(actions_pane_3Layout);
        actions_pane_3Layout.setHorizontalGroup(
            actions_pane_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_pane_3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(segmentPane_save)
                .addGap(18, 18, 18)
                .addComponent(segmentPane_duplicate)
                .addGap(82, 82, 82)
                .addComponent(segmentPane_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(segmentPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actions_pane_3Layout.setVerticalGroup(
            actions_pane_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actions_pane_3Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(actions_pane_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(segmentPane_save)
                    .addComponent(segmentPane_duplicate)
                    .addComponent(segmentPane_delete)
                    .addComponent(segmentPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        segment_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        segment_table.setViewportView(segment_jtable);

        javax.swing.GroupLayout segment_paneLayout = new javax.swing.GroupLayout(segment_pane);
        segment_pane.setLayout(segment_paneLayout);
        segment_paneLayout.setHorizontalGroup(
            segment_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, segment_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(segment_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(segment_table)
                    .addComponent(segment_fields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actions_pane_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 912, Short.MAX_VALUE))
                .addContainerGap())
        );
        segment_paneLayout.setVerticalGroup(
            segment_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(segment_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(segment_fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actions_pane_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(segment_table, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        main_tab.addTab("Ségments", segment_pane);

        jLabel15.setText("ID");

        workplacePane_field_id.setEditable(false);

        jLabel16.setText("Projet");

        jLabel17.setText("Workplace");

        jLabel29.setText("Ségment");

        javax.swing.GroupLayout workplace_fieldsLayout = new javax.swing.GroupLayout(workplace_fields);
        workplace_fields.setLayout(workplace_fieldsLayout);
        workplace_fieldsLayout.setHorizontalGroup(
            workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workplace_fieldsLayout.createSequentialGroup()
                .addGroup(workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(workplacePane_field_project, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workplacePane_field_id, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(workplacePane_field_segment, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workplacePane_field_workplace))
                .addContainerGap(539, Short.MAX_VALUE))
        );
        workplace_fieldsLayout.setVerticalGroup(
            workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workplace_fieldsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workplacePane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workplacePane_field_project, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workplacePane_field_segment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(workplace_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(workplacePane_field_workplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        workplacePane_msg.setEditable(false);
        workplacePane_msg.setBackground(new java.awt.Color(255, 255, 255));
        workplacePane_msg.setForeground(new java.awt.Color(0, 0, 0));
        workplacePane_msg.setCaretColor(new java.awt.Color(255, 255, 255));

        workplacePane_delete.setText("Supprimer");

        workplacePane_duplicate.setText("Dupliquer");

        workplacePane_save.setText("Enregistrer");

        workplace_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        workplace_table.setViewportView(workplace_jtable);

        javax.swing.GroupLayout actions_pane_4Layout = new javax.swing.GroupLayout(actions_pane_4);
        actions_pane_4.setLayout(actions_pane_4Layout);
        actions_pane_4Layout.setHorizontalGroup(
            actions_pane_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_pane_4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workplacePane_save)
                .addGap(18, 18, 18)
                .addComponent(workplacePane_duplicate)
                .addGap(82, 82, 82)
                .addComponent(workplacePane_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workplacePane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
            .addComponent(workplace_table)
        );
        actions_pane_4Layout.setVerticalGroup(
            actions_pane_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actions_pane_4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(actions_pane_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(workplacePane_save)
                    .addComponent(workplacePane_duplicate)
                    .addComponent(workplacePane_delete)
                    .addComponent(workplacePane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(workplace_table, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout workplace_paneLayout = new javax.swing.GroupLayout(workplace_pane);
        workplace_pane.setLayout(workplace_paneLayout);
        workplace_paneLayout.setHorizontalGroup(
            workplace_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, workplace_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(workplace_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(workplace_fields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actions_pane_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        workplace_paneLayout.setVerticalGroup(
            workplace_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(workplace_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(workplace_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actions_pane_4, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        main_tab.addTab("Wokrplaces", workplace_pane);

        jLabel18.setText("ID");

        magasinPane_field_id.setEditable(false);

        jLabel19.setText("Projet");

        jLabel20.setText("Magasin");

        jLabel22.setText("Description");

        magasinPane_field_WhType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PACKAGING", "FINISH GOODS", "TRANSIT", "INVENTORY", "SCRAP" }));

        jLabel23.setText("Type");

        magasinPane_field_desc.setColumns(20);
        magasinPane_field_desc.setRows(2);
        magasinPane_field_desc.setToolTipText("");
        magasinPane_field_desc.setAutoscrolls(false);
        jScrollPane1.setViewportView(magasinPane_field_desc);

        javax.swing.GroupLayout magasin_fieldsLayout = new javax.swing.GroupLayout(magasin_fields);
        magasin_fields.setLayout(magasin_fieldsLayout);
        magasin_fieldsLayout.setHorizontalGroup(
            magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(magasin_fieldsLayout.createSequentialGroup()
                .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(magasinPane_field_projet, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(magasinPane_field_id)
                    .addComponent(magasinPane_field_magasin, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(131, 131, 131)
                .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(magasin_fieldsLayout.createSequentialGroup()
                        .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magasinPane_field_WhType, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        magasin_fieldsLayout.setVerticalGroup(
            magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, magasin_fieldsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(magasin_fieldsLayout.createSequentialGroup()
                        .addComponent(magasinPane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magasinPane_field_projet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(magasinPane_field_magasin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(magasin_fieldsLayout.createSequentialGroup()
                        .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(magasinPane_field_WhType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(magasin_fieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(31, 31, 31))
        );

        magasinPane_msg.setEditable(false);
        magasinPane_msg.setBackground(new java.awt.Color(255, 255, 255));
        magasinPane_msg.setForeground(new java.awt.Color(0, 0, 0));

        magasinPane_delete.setText("Supprimer");

        magasinPane_duplicate.setText("Dupliquer");

        magasinPane_save.setText("Enregistrer");

        javax.swing.GroupLayout actions_pane_5Layout = new javax.swing.GroupLayout(actions_pane_5);
        actions_pane_5.setLayout(actions_pane_5Layout);
        actions_pane_5Layout.setHorizontalGroup(
            actions_pane_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_pane_5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(magasinPane_save)
                .addGap(18, 18, 18)
                .addComponent(magasinPane_duplicate)
                .addGap(82, 82, 82)
                .addComponent(magasinPane_delete)
                .addGap(18, 18, 18)
                .addComponent(magasinPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        actions_pane_5Layout.setVerticalGroup(
            actions_pane_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actions_pane_5Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(actions_pane_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(magasinPane_save)
                    .addComponent(magasinPane_duplicate)
                    .addComponent(magasinPane_delete)
                    .addComponent(magasinPane_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        magasin_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        magasin_jtable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        magasin_table.setViewportView(magasin_jtable);

        javax.swing.GroupLayout magasin_paneLayout = new javax.swing.GroupLayout(magasin_pane);
        magasin_pane.setLayout(magasin_paneLayout);
        magasin_paneLayout.setHorizontalGroup(
            magasin_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(magasin_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(magasin_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(magasin_table)
                    .addGroup(magasin_paneLayout.createSequentialGroup()
                        .addGroup(magasin_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(magasin_fields, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(actions_pane_5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        magasin_paneLayout.setVerticalGroup(
            magasin_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(magasin_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(magasin_fields, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actions_pane_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(magasin_table, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE))
        );

        main_tab.addTab("Magasins", magasin_pane);

        transporterPane_label_id.setText("ID");

        transporterPane_field_id.setEditable(false);

        javax.swing.GroupLayout project_fields1Layout = new javax.swing.GroupLayout(project_fields1);
        project_fields1.setLayout(project_fields1Layout);
        project_fields1Layout.setHorizontalGroup(
            project_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(project_fields1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transporterPane_label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transporterPane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        project_fields1Layout.setVerticalGroup(
            project_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, project_fields1Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addGroup(project_fields1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transporterPane_label_id, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transporterPane_field_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        transporterPane_field_msg.setEditable(false);
        transporterPane_field_msg.setBackground(new java.awt.Color(255, 255, 255));
        transporterPane_field_msg.setForeground(new java.awt.Color(0, 0, 0));

        transporterPane_delete.setText("Supprimer");

        transporterPane_duplicate.setText("Dupliquer");

        transporterPane_save.setText("Enregistrer");

        javax.swing.GroupLayout actions_pane_6Layout = new javax.swing.GroupLayout(actions_pane_6);
        actions_pane_6.setLayout(actions_pane_6Layout);
        actions_pane_6Layout.setHorizontalGroup(
            actions_pane_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actions_pane_6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transporterPane_save)
                .addGap(18, 18, 18)
                .addComponent(transporterPane_duplicate)
                .addGap(82, 82, 82)
                .addComponent(transporterPane_delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transporterPane_field_msg, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        actions_pane_6Layout.setVerticalGroup(
            actions_pane_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actions_pane_6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(actions_pane_6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(transporterPane_save)
                    .addComponent(transporterPane_duplicate)
                    .addComponent(transporterPane_delete)
                    .addComponent(transporterPane_field_msg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        transporter_jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        transporter_jtable.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        transporter_table.setViewportView(transporter_jtable);

        javax.swing.GroupLayout transporter_paneLayout = new javax.swing.GroupLayout(transporter_pane);
        transporter_pane.setLayout(transporter_paneLayout);
        transporter_paneLayout.setHorizontalGroup(
            transporter_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transporter_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(transporter_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(transporter_table)
                    .addComponent(project_fields1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(actions_pane_6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        transporter_paneLayout.setVerticalGroup(
            transporter_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transporter_paneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(project_fields1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(actions_pane_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transporter_table, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );

        main_tab.addTab("Transporteurs", transporter_pane);

        segmentPane_msg1.setEditable(false);
        segmentPane_msg1.setBackground(new java.awt.Color(255, 255, 255));
        segmentPane_msg1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(main_tab)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(176, 176, 176)
                    .addComponent(segmentPane_msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(main_tab))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(segmentPane_msg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(652, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void famillePane_field_scan_modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_famillePane_field_scan_modeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_famillePane_field_scan_modeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actions_pane;
    private javax.swing.JPanel actions_pane_2;
    private javax.swing.JPanel actions_pane_3;
    private javax.swing.JPanel actions_pane_4;
    private javax.swing.JPanel actions_pane_5;
    private javax.swing.JPanel actions_pane_6;
    private javax.swing.JPanel actions_pane_7;
    private javax.swing.JButton companyPane_btn_delete;
    private javax.swing.JButton companyPane_btn_duplicate;
    private javax.swing.JButton companyPane_btn_save;
    private javax.swing.JTextField companyPane_field_address1;
    private javax.swing.JTextField companyPane_field_address2;
    private javax.swing.JTextField companyPane_field_city;
    private javax.swing.JTextField companyPane_field_country;
    private javax.swing.JTextField companyPane_field_description;
    private javax.swing.JTextField companyPane_field_id;
    private javax.swing.JTextField companyPane_field_name;
    private javax.swing.JTextField companyPane_field_website;
    private javax.swing.JTextField companyPane_field_zip;
    private javax.swing.JTextField companyPane_msg;
    private javax.swing.JPanel company_fields;
    private javax.swing.JTable company_jtable;
    private javax.swing.JPanel company_pane;
    private javax.swing.JScrollPane company_table;
    private javax.swing.JButton famillePane_delete;
    private javax.swing.JButton famillePane_duplicate;
    private javax.swing.JTextField famillePane_field_family;
    private javax.swing.JTextField famillePane_field_id;
    private javax.swing.JComboBox<String> famillePane_field_project;
    private javax.swing.JComboBox<String> famillePane_field_scan_mode;
    private javax.swing.JTextField famillePane_msg;
    private javax.swing.JButton famillePane_save;
    private javax.swing.JTable famille_jtable;
    private javax.swing.JScrollPane famille_table;
    private javax.swing.JPanel family_fields;
    private javax.swing.JPanel family_fields1;
    private javax.swing.JPanel family_pane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton magasinPane_delete;
    private javax.swing.JButton magasinPane_duplicate;
    private javax.swing.JComboBox<String> magasinPane_field_WhType;
    private javax.swing.JTextArea magasinPane_field_desc;
    private javax.swing.JTextField magasinPane_field_id;
    private javax.swing.JTextField magasinPane_field_magasin;
    private javax.swing.JComboBox<String> magasinPane_field_projet;
    private javax.swing.JTextField magasinPane_msg;
    private javax.swing.JButton magasinPane_save;
    private javax.swing.JPanel magasin_fields;
    private javax.swing.JTable magasin_jtable;
    private javax.swing.JPanel magasin_pane;
    private javax.swing.JScrollPane magasin_table;
    private javax.swing.JTabbedPane main_tab;
    private javax.swing.JButton projectPane_delete;
    private javax.swing.JButton projectPane_duplicate;
    private javax.swing.JTextField projectPane_field_id;
    private javax.swing.JTextField projectPane_field_id2;
    private javax.swing.JTextField projectPane_msg;
    private javax.swing.JButton projectPane_save;
    private javax.swing.JPanel project_fields1;
    private javax.swing.JTable project_jtable;
    private javax.swing.JPanel project_pane;
    private javax.swing.JScrollPane project_table;
    private javax.swing.JButton segmentPane_delete;
    private javax.swing.JButton segmentPane_duplicate;
    private javax.swing.JTextField segmentPane_field_id;
    private javax.swing.JComboBox<String> segmentPane_field_project;
    private javax.swing.JTextField segmentPane_field_segment;
    private javax.swing.JTextField segmentPane_msg;
    private javax.swing.JTextField segmentPane_msg1;
    private javax.swing.JButton segmentPane_save;
    private javax.swing.JPanel segment_fields;
    private javax.swing.JTable segment_jtable;
    private javax.swing.JPanel segment_pane;
    private javax.swing.JScrollPane segment_table;
    private javax.swing.JButton transporterPane_delete;
    private javax.swing.JButton transporterPane_duplicate;
    private javax.swing.JTextField transporterPane_field_id;
    private javax.swing.JTextField transporterPane_field_msg;
    private javax.swing.JLabel transporterPane_label_id;
    private javax.swing.JButton transporterPane_save;
    private javax.swing.JTable transporter_jtable;
    private javax.swing.JPanel transporter_pane;
    private javax.swing.JScrollPane transporter_table;
    private javax.swing.JButton workplacePane_delete;
    private javax.swing.JButton workplacePane_duplicate;
    private javax.swing.JTextField workplacePane_field_id;
    private javax.swing.JComboBox<String> workplacePane_field_project;
    private javax.swing.JComboBox<String> workplacePane_field_segment;
    private javax.swing.JTextField workplacePane_field_workplace;
    private javax.swing.JTextField workplacePane_msg;
    private javax.swing.JButton workplacePane_save;
    private javax.swing.JPanel workplace_fields;
    private javax.swing.JTable workplace_jtable;
    private javax.swing.JPanel workplace_pane;
    private javax.swing.JScrollPane workplace_table;
    // End of variables declaration//GEN-END:variables
}
